### ISSUE TITLE
Select Bluetooth adapter

### ISSUE THREAD

**Issue by gustjoha** [sanjay900/igrill#1]
Hi,

Would it be possible to select BLE adapter similar to how [ble_monitor](https://github.com/custom-components/ble_monitor) makes it possible? I have two adapters (one crap on-board one and one external in a dongle) and disabling one in HA is a pain..

**Comment by sanjay900** [comment]
ill see if i can work out how to do that

**Comment by sanjay900** [comment]
I have some other bugs to work through first ,as it seems that porting everything to bleak caused issues

**Comment by sanjay900** [comment]
I don't have two adapters to test this myself, but in theory you should be able to pick an adapter now with the latest commit
I think ive also fixed the bleak issues too

**Comment by gustjoha** [comment]
Hi,

Tried it now but upon hitting Submit it gives me "Unknown Error occured".

**Comment by sanjay900** [comment]
do you get a stack trace?

**Comment by sanjay900** [comment]
Ah i see the issue, try that version

**Comment by sanjay900** [comment]
I will probably redo this integration with the new bluetooth stuff in home assistant though in the future, but it should be working for the moment

annoyingly i cant seem to find any documentation on the new bluetooth stuff though :(

**Comment by sanjay900** [comment]
I also bumped the bluetooth libraries so it should work with the latest version of home assistant too

**Comment by sanjay900** [comment]
Just did a total rewrite, this should now be handled by however home assistant handles it, as i am now doing things the same way all the built in home assistant bluetooth integrations work. 

I realise now that the rewrite relies on some features from the next version of home assistant so you won't be able to use it yet.

**Comment by gustjoha** [comment]
This is very cool, I will test it next time I´m grilling! I haven´t been able to test for a while as my iGrill started acting up in general.

**Comment by sanjay900** [comment]
I rewrote the entire thing again, it now works on the current version of home assistant, and should be a lot more optimised. It no longer polls, it waits for the sensor to push updates which makes temperature updates very snappy.
