### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by anthonyangel** [sanjay900/igrill#2]
Hi, thanks very much for making this - it's great!

I've loaded up your custom component using a USB bluetooth adaptor, and received an authentication failure when trying to connect to an iGrill2

```
Traceback (most recent call last):
  File "/config/custom_components/igrill_ble/igrill.py", line 197, in async_init
    BleakClient, ble_device, ble_device.address, lambda device: self._on_disconnect(device)
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 411, in pair
    return await self._backend.pair(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 396, in pair
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.AuthenticationFailed] Authentication Failed
```

I opened up terminal, ran `bluetoothctl`, `scan on`, `pair <mac address>` and it now works as expected

**Comment by sanjay900** [comment]
weird, no idea why its doing that.

**Comment by anthonyangel** [comment]
I've done it once, and it seems fine. Hopefully this helps the next person in case it happens again!

**Comment by KennyHec** [comment]
thank allot @anthonyangel , been plagued by this for a while, now i finnaly got it working.
@sanjay900 maybe add this to the readme?

**Comment by sanjay900** [comment]
> thank allot @anthonyangel , been plagued by this for a while, now i finnaly got it working. @sanjay900 maybe add this to the readme?

done
